version: "3.7"
services:
  back:
    container_name: garden-back
    build: 
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8900"
    volumes:
      - ./back/pb_data/:/pb_data/
  front:
    container_name: garden-front
    build: 
      context: ./front
      dockerfile: Dockerfile
    environment:
      - PUBLIC_POCKETBASE_URL:http://127.0.0.1:8090
    ports:
      - "3000:5173"
    depends_on:
      - back
  

