version: "3.7"
services:
  back:
    container_name: garden-back
    build: 
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8078:8900"
    volumes:
      - ./back/pb_data/:/pb_data/
  front:
    container_name: garden-front
    build: 
      context: ./front
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:5173"
    depends_on:
      - back
  

